keyboards:
  sofle:
    # Sofle RGB 2.1 + Nice!nano v2
    board: nice_nano_v2
    shield: sofle_left
    config: sofle.conf
    keymap: sofle
    artifact-name: sofle-nice_nano_v2
    left-zip: sofle_nice_nano_v2_left.uf2
    right-zip: sofle_nice_nano_v2_right.uf2

